FROM node:12-alpine
EXPOSE 3000 6379 50051 8080

RUN npm install -g typescript
RUN npm install -g ts-node
RUN npm install -g ts-node-dev

# nest
RUN npm install -g @nestjs/cli

# prisma
RUN npm install -g prisma

RUN npm install -g graphql-cli