FROM node:latest
EXPOSE 3000 27017
RUN npm install bcrypt
RUN npm install -g ts-node
RUN npm install -g typescript
RUN npm install -g ts-node-dev

# npm update all
RUN npm install -g outdate
RUN npm install -g ncu

# prisma
RUN npm install -g prisma
RUN npm install -g graphql-cli

# nest
RUN npm install -g @nestjs/cli