FROM node:11-alpine
EXPOSE 3000 27017
# RUN npm install bcrypt
RUN npm install -g ts-node
RUN npm install -g typescript
RUN npm install -g ts-node-dev

# npm update all
RUN npm install -g outdate
RUN npm install -g ncu

# nest
RUN npm install -g @nestjs/cli

# RUN npm install grpc --build-from-source
